spring:
  application:
    name: zuul-service
server:
  port: 8762
eureka:
  instance:
    preferIpAddress: true
  serviceurl:
    defaultzone: http://localhost:8761/eureka/
  client:
    registerWithEureka: true
    fetchRegistry: true